#!/bin/bash

#SBATCH --partition=long-cpu
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --mem=16G
#SBATCH --time=50:00:00
#SBATCH --cpus-per-task=4
#SBATCH -o /network/scratch/f/faisal.mohamed/slurm-%j.out  # Write the log on scratch

# 1. Load your environment
module load anaconda/3
conda activate /home/mila/f/faisal.mohamed/.conda/envs/cleanrl
export WANDB_DIR=$SCRATCH
export WANDB_MODE=online



# 4. Launch your job
python $1 $2 $3 $4 $5 $6 $7 $8 ${9} ${10} ${11} ${12} ${13} ${14} ${15} ${16} ${17} ${18} ${19} ${20} ${21} ${22} ${23} ${24} ${25} ${26} ${27} ${28} ${29} ${30} ${31} ${32} ${33} ${34} ${35} ${36} ${37} ${38} ${39} ${40} ${41} ${42} ${43} ${44} ${45} ${46} ${47} ${48} ${49} ${50} ${51} 